# Generated by Django 4.2.7 on 2025-05-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0013_add_organization_fk_to_auditlog'),
        ('products', '10012_rename_products_pr_categor_14b9c0_idx_products_pr_categor_9edb3d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('iso_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Price Type',
                'verbose_name_plural': 'Price Types',
                'ordering': ['label'],
                'unique_together': {('code', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_entries', to='products.saleschannel')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prices.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_entries', to='organizations.organization')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prices.pricetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['product', 'price_type'], name='prices_prod_product_bb9405_idx')],
                'unique_together': {('product', 'price_type', 'channel', 'valid_from')},
            },
        ),
    ]
