# Generated by Django 4.2.20 on 2025-05-02 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_seed_default_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
