# Generated by Django 4.2.20 on 2025-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_uuid_schema_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
