# Generated by Django 4.2.20 on 2025-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organizations", "0007_convert_to_integer_id")]
    operations = [
        migrations.AddField(
            model_name="organization",
            name="int_id",
            field=models.AutoField(null=True),
        ),
    ] 