# Generated by Django 4.2.20 on 2025-05-03 15:01

from django.db import migrations

def backfill_int_id(apps, schema_editor):
    """
    Populate the int_id field with auto-incrementing values for each organization
    """
    Organization = apps.get_model('organizations', 'Organization')
    
    # Use enumerate to generate sequential integers 
    for i, org in enumerate(Organization.objects.all(), start=1):
        org.int_id = i
        org.save(update_fields=['int_id'])


class Migration(migrations.Migration):
    dependencies = [("organizations", "0008_add_int_id")]
    operations = [
        migrations.RunPython(
            backfill_int_id,
            reverse_code=migrations.RunPython.noop
        ),
    ] 