# Generated by Django 4.2.20 on 2025-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organizations", "0010_update_foreign_keys")]
    operations = [
        # Step 1: Make old UUID field non-primary key and rename it 
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        
        migrations.RenameField(
            model_name="organization",
            old_name="id",
            new_name="uuid_id_old",
        ),
        
        # Step 2: Make int_id the new PK
        migrations.AlterField(
            model_name="organization",
            name="int_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        
        # Step 3: Rename int_id to id
        migrations.RenameField(
            model_name="organization",
            old_name="int_id",
            new_name="id",
        ),
        
        # Step 4: Delete old UUID field
        migrations.RemoveField(
            model_name="organization",
            name="uuid_id_old",
        ),
    ] 