# Generated by Django 4.2.20 on 2025-05-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_cleanup_org_fields"),
        ("organizations", "0011_finalize_primary_key"),
    ]

    operations = []
