# Generated by Django 4.2.20 on 2025-05-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_merge_20250503_1336"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="uuid",
        ),
    ]
