# Generated by Django 4.2.7 on 2025-05-15 14:30

from django.db import migrations, models
import django.db.models.deletion


def backfill_defaults(apps, schema_editor):
    """
    Backfill default_locale with 'en_US' and default_channel with the first active channel.
    """
    Organization = apps.get_model('organizations', 'Organization')
    SalesChannel = apps.get_model('products', 'SalesChannel')
    
    # For each organization, set the default locale and find an appropriate channel
    for org in Organization.objects.all():
        # Set default locale to en_US
        org.default_locale = 'en_US'
        
        # Find the first active channel for this organization
        default_channel = SalesChannel.objects.filter(
            organization=org,
            is_active=True
        ).first()
        
        # If found, set it as the default channel
        if default_channel:
            org.default_channel = default_channel
        
        # Save the updates
        org.save()


def reverse_migration(apps, schema_editor):
    """
    No need to reverse the data migration as the fields will be removed.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10006_add_price_models'),  # Make sure SalesChannel exists
        ('organizations', '0013_add_organization_fk_to_auditlog'),
    ]

    operations = [
        # First, add the fields
        migrations.AddField(
            model_name='organization',
            name='default_locale',
            field=models.CharField(
                choices=[
                    ('en_US', 'English (US)'),
                    ('fr_FR', 'French'),
                    ('es_ES', 'Spanish'),
                    ('de_DE', 'German'),
                    ('it_IT', 'Italian'),
                    ('ja_JP', 'Japanese'),
                    ('ko_KR', 'Korean'),
                    ('pt_BR', 'Portuguese (Brazil)'),
                    ('ru_RU', 'Russian'),
                    ('zh_CN', 'Chinese (Simplified)')
                ],
                default='en_US',
                help_text='Fallback locale for this organization',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_channel',
            field=models.ForeignKey(
                blank=True,
                help_text='Fallback sales channel for this organization',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='products.saleschannel'
            ),
        ),
        
        # Then, run the data migration
        migrations.RunPython(backfill_defaults, reverse_migration),
    ] 