# Generated by Django 4.2.7 on 2025-05-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_attributevalue_locale_code'),
        ('organizations', '0014_add_default_locale_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_locale_ref',
            field=models.ForeignKey(blank=True, help_text='Fallback locale for this organization (preferred over default_locale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='products.locale'),
        ),
    ]
