# Generated by Django 4.2.20 on 2025-04-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
    ]
