# Generated by Django 4.2.20 on 2025-04-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_stock_and_type_fields"),
    ]

    operations = []
