# Generated by Django 4.2.20 on 2025-04-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_auto_20250425_2011"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="country_availability",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit_of_measure",
        ),
    ]
