# Generated by Django 4.2.20 on 2025-04-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_organization_remove_user_created_at_remove_user_name_and_more",
        ),
        ("products", "0013_unique_sku_per_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="uq_product_user_sku",
        ),
        migrations.AddField(
            model_name="product",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="productasset",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="productasset",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_assets",
                to="accounts.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_archived"], name="products_pr_is_arch_b791cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["organization"], name="products_pr_organiz_d1a778_idx"
            ),
        ),
    ]
