# Generated by Django 4.2.20 on 2025-05-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_init_org"),
        ("products", "0014_add_product_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="productasset",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="productevent",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="productrelation",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
    ]
