# Generated by Django 4.2.20 on 2025-05-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_seed_default_org"),
        ("products", "0015_add_org_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("organization", "sku")},
        ),
    ]
