# Generated by Django 4.2.20 on 2025-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_product_options_alter_product_unique_together"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_pr_price_9b1a5f_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["organization"], name="products_pr_organiz_d1a778_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["organization", "sku"], name="products_pr_organiz_88bfd9_idx"
            ),
        ),
    ]
