# Generated by Django 4.2.7 on 2025-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_link_attributevalue_to_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='locale_code',
            field=models.CharField(blank=True, help_text="Legacy locale code field, use 'locale' instead", max_length=10, null=True),
        ),
    ]
