# Generated by Django 4.2.20 on 2025-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "10004_attributevalue_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrelation",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the relationship between these products",
                null=True,
            ),
        ),
    ]
