# Generated by Django 4.2.20 on 2025-05-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_update_attributevalue_constraints"),
        ("products", "10001_set_null_orders_to_zero"),
    ]

    operations = []
