# Generated by Django 4.2.7 on 2025-05-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10007_backfill_product_prices'),
    ]

    operations = [
        # Empty migration to serve as a dependency for 10010_alter_product_price
    ] 