# Generated by Django 4.2.7 on 2025-05-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10014_add_new_attribute_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(
                choices=[
                    ('text', 'Text'), 
                    ('number', 'Number'), 
                    ('boolean', 'Boolean'),
                    ('date', 'Date'), 
                    ('select', 'Select'),
                    ('rich_text', 'Rich Text'),
                    ('price', 'Price'),
                    ('media', 'Media'),
                    ('measurement', 'Measurement'),
                    ('url', 'URL'),
                    ('email', 'Email'),
                    ('phone', 'Phone'),
                ],
                max_length=16
            ),
        ),
    ]
