# Generated by Django 4.2.7 on 2025-05-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10015_manual_remove_product_price'),
        ('products', '10015_remove_product_price'),
    ]

    operations = [
    ]
