# Generated by Django 4.2.7 on 2025-05-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10011_add_category_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_9edb3d_idx',
            old_name='products_pr_categor_14b9c0_idx',
        ),
    ]
