# Generated by Django 4.2.7 on 2025-05-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_migrate_legacy_prices_to_base'),
        ('products', '10013_migrate_price_type_and_currency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productprice',
            new_name='products_pr_price_t_ca46c8_idx',
            old_name='products_pr_price_t_8b3fcf_idx',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='product_app_prices', to='prices.currency'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_type',
            field=models.ForeignKey(db_column='price_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='product_app_prices', to='prices.pricetype'),
        ),
    ]
