# Generated by Django 4.2.7 on 2025-05-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10017_merge_20250511_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.attribute')),
            ],
            options={
                'ordering': ['attribute', 'order', 'id'],
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
