# Generated by Django 4.2.7 on 2025-05-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10016_merge'),
        ('products', '10016_merge_20250510_2250'),
    ]

    operations = [
    ]
