# Generated by Django 4.2.7 on 2025-05-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10012_rename_products_pr_categor_14b9c0_idx_products_pr_categor_9edb3d_idx'),
    ]

    operations = [
    ]
