# Generated by Django 4.2.7 on 2025-05-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10009_make_price_field_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
