# Generated by Django 4.2.7 on 2025-05-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_migrate_legacy_prices_to_base'),
        ('products', '10013_merge_0018_10012'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_price_9b1a5f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_9edb3d_idx',
            old_name='products_pr_categor_14b9c0_idx',
        ),
        migrations.RenameIndex(
            model_name='productprice',
            new_name='products_pr_price_t_ca46c8_idx',
            old_name='products_pr_price_t_8b3fcf_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('select', 'Select'), ('rich_text', 'Rich Text'), ('price', 'Price'), ('media', 'Media'), ('measurement', 'Measurement'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Phone')], max_length=16),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='product_app_prices', to='prices.currency'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_type',
            field=models.ForeignKey(db_column='price_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='product_app_prices', to='prices.pricetype'),
        ),
    ]
