# Generated by Django 4.2.7 on 2025-05-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10014_remove_product_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_price_9b1a5f_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
