# Generated by Django 4.2.7 on 2025-05-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10015_add_new_attribute_types_clean'),
        ('products', '10016_add_attribute_types_fixed'),
    ]

    operations = [
    ]
