# Generated by Django 4.2.7 on 2025-05-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10018_attributeoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ManyToManyField(related_name='bundles', to='products.productasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='products.product')),
            ],
        ),
    ]
