# Generated by Django 4.2.7 on 2025-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10019_assetbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasset',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags associated with this asset'),
        ),
    ]
