# Generated by Django 4.2.7 on 2025-05-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_add_organization_fk_to_auditlog'),
        ('products', '10021_add_family_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamilyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=True)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributegroup')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_overrides', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Family Override',
                'verbose_name_plural': 'Product Family Overrides',
                'unique_together': {('product', 'attribute_group')},
            },
        ),
    ]
