# Generated by Django 4.2.7 on 2025-05-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_add_default_locale_channel'),
        ('products', '10025_alter_productfamilyoverride_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Locale',
                'verbose_name_plural': 'Locales',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['organization'], name='products_lo_organiz_f6f6d6_idx'), models.Index(fields=['code'], name='products_lo_code_5761d6_idx')],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
