# Generated by Django 4.2.7 on 2025-05-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_add_created_desc_idx'),
        ('products', '10026_add_version_to_family'),
    ]

    operations = [
    ]
