# Generated by Django 4.2.20 on 2025-05-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "10002_merge_20250502_1606"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimAttribute",
            fields=[
                (
                    "attribute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="products.attribute",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("data_type", models.CharField(max_length=16)),
                ("organization_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Attribute Dimension",
                "verbose_name_plural": "Attribute Dimensions",
            },
        ),
        migrations.CreateModel(
            name="DimChannel",
            fields=[
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Channel Dimension",
                "verbose_name_plural": "Channel Dimensions",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DimLocale",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Locale Dimension",
                "verbose_name_plural": "Locale Dimensions",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DimProduct",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("sku", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("organization_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Product Dimension",
                "verbose_name_plural": "Product Dimensions",
            },
        ),
        migrations.CreateModel(
            name="DimTime",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
            ],
            options={
                "verbose_name": "Time Dimension",
                "verbose_name_plural": "Time Dimensions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FactProductAttribute",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("organization_id", models.IntegerField()),
                ("value", models.JSONField()),
                ("completed", models.BooleanField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimattribute",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimchannel",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimlocale",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimproduct",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.dimtime",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute Fact",
                "verbose_name_plural": "Product Attribute Facts",
                "indexes": [
                    models.Index(
                        fields=["time"], name="analytics_f_time_id_a7891d_idx"
                    ),
                    models.Index(
                        fields=["attribute"], name="analytics_f_attribu_45bcc3_idx"
                    ),
                    models.Index(
                        fields=["product"], name="analytics_f_product_52675f_idx"
                    ),
                    models.Index(
                        fields=["organization_id"],
                        name="analytics_f_organiz_1ba096_idx",
                    ),
                ],
                "unique_together": {
                    ("product", "attribute", "time", "locale", "channel")
                },
            },
        ),
    ]
