# Generated by Django 4.2.20 on 2025-05-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimEditor",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Editor Dimension",
                "verbose_name_plural": "Editor Dimensions",
                "ordering": ["username"],
            },
        ),
        migrations.AddField(
            model_name="factproductattribute",
            name="edit_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this attribute has been edited"
            ),
        ),
        migrations.AddField(
            model_name="factproductattribute",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this attribute was first published",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="factproductattribute",
            name="is_translated",
            field=models.BooleanField(
                default=False,
                help_text="Whether this attribute has been translated for the given locale",
            ),
        ),
        migrations.AddField(
            model_name="factproductattribute",
            name="translated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this attribute was last translated",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="factproductattribute",
            index=models.Index(
                fields=["edit_count"], name="analytics_f_edit_co_02eb88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factproductattribute",
            index=models.Index(
                fields=["first_published_at"], name="analytics_f_first_p_0a5f37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factproductattribute",
            index=models.Index(
                fields=["is_translated"], name="analytics_f_is_tran_118985_idx"
            ),
        ),
        migrations.AddField(
            model_name="factproductattribute",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_attributes",
                to="analytics.dimeditor",
            ),
        ),
    ]
