# Generated by Django 4.2.20 on 2025-05-02 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                default=teams.models.get_default_org,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="org_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "organization")},
        ),
    ]
