# Generated by Django 3.2.10 on 2023-07-25 18:25

from django.db import migrations
from teams.constants import DEFAULT_ROLE_PERMISSIONS

def create_and_seed_roles(apps, schema_editor):
    """Create default roles with permissions if they don't exist"""
    Role = apps.get_model("teams", "Role")
    for role_name, perms in DEFAULT_ROLE_PERMISSIONS.items():
        role, created = Role.objects.get_or_create(name=role_name)
        # Only overwrite if it's new or empty
        if created or not role.permissions:
            role.permissions = perms
            role.save(update_fields=["permissions"])

def reverse_seed(apps, schema_editor):
    """No need to remove the roles on reverse migration"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_backfill_auditlog_organization'),
    ]

    operations = [
        migrations.RunPython(create_and_seed_roles, reverse_seed),
    ] 