# Generated by Django 4.2.20 on 2025-04-29 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="imports/")),
                ("mapping", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial_success", "Partial Success"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=15,
                    ),
                ),
                ("processed", models.PositiveIntegerField(default=0)),
                ("total_rows", models.PositiveIntegerField(null=True)),
                (
                    "error_file",
                    models.FileField(null=True, upload_to="imports/errors/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True, help_text="Execution time in seconds", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
