# Generated by Django 4.2.20 on 2025-05-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_init_org"),
        ("imports", "0002_add_duplicate_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="importtask",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
    ]
