# Generated by Django 4.2.7 on 2025-05-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_update_product_price_model'),
        ('products', '10014_prepare_price_type_and_currency_data'),
    ]

    operations = [
        # 1. Add temporary columns
        migrations.RunSQL(
            """
            -- Add temp_price_type_id column
            ALTER TABLE products_productprice ADD COLUMN temp_price_type_id integer;
            
            -- Add temp_currency_id column
            ALTER TABLE products_productprice ADD COLUMN temp_currency_id character varying(3);
            """,
            reverse_sql="ALTER TABLE products_productprice DROP COLUMN IF EXISTS temp_price_type_id, DROP COLUMN IF EXISTS temp_currency_id;"
        ),
        
        # 2. Populate the temp columns from related tables
        migrations.RunSQL(
            """
            -- For each product price, find the matching price type and update temp_price_type_id
            UPDATE products_productprice pp 
            SET temp_price_type_id = pt.id
            FROM prices_pricetype pt
            WHERE pp.price_type = pt.code 
              AND pp.organization_id = pt.organization_id;
            
            -- For any missing price types, try to find any price type with the same code
            UPDATE products_productprice pp
            SET temp_price_type_id = pt.id
            FROM prices_pricetype pt
            WHERE pp.temp_price_type_id IS NULL
              AND pp.price_type = pt.code
              AND pt.id IN (SELECT MIN(id) FROM prices_pricetype WHERE code = pt.code GROUP BY code);
            
            -- For any still missing price types, use MSRP or list as fallback
            UPDATE products_productprice pp
            SET temp_price_type_id = (
                SELECT id FROM prices_pricetype 
                WHERE code IN ('list', 'msrp') 
                  AND organization_id = pp.organization_id
                ORDER BY code = 'list' DESC
                LIMIT 1
            )
            WHERE pp.temp_price_type_id IS NULL AND pp.organization_id IS NOT NULL;
            
            -- For currencies, find matching currency for this org
            UPDATE products_productprice pp
            SET temp_currency_id = c.iso_code
            FROM prices_currency c
            WHERE pp.currency = c.iso_code
              AND pp.organization_id = c.organization_id;
              
            -- For any missing currencies, try to find any currency with same code
            UPDATE products_productprice pp
            SET temp_currency_id = c.iso_code
            FROM prices_currency c
            WHERE pp.temp_currency_id IS NULL
              AND pp.currency = c.iso_code
            LIMIT 1;
            
            -- For any still missing currencies, use USD
            UPDATE products_productprice pp
            SET temp_currency_id = 'USD'
            WHERE pp.temp_currency_id IS NULL;
            """,
            reverse_sql=""
        ),
    ] 