# Generated by Django 4.2.7 on 2025-05-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10012_rename_products_pr_categor_14b9c0_idx_products_pr_categor_9edb3d_idx'),
    ]

    operations = [
        # This is a dummy migration that was created to fix a migration dependency issue
    ] 