# Generated by Django 4.2.7 on 2025-05-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '10016_connect_to_price_models'),
    ]

    operations = [
        # 3. Remove the original columns and rename the temp columns
        migrations.RunSQL(
            """
            -- Drop the old columns
            ALTER TABLE products_productprice DROP COLUMN price_type;
            ALTER TABLE products_productprice DROP COLUMN currency;
            
            -- Rename the temp columns
            ALTER TABLE products_productprice RENAME COLUMN temp_price_type_id TO price_type_id;
            ALTER TABLE products_productprice RENAME COLUMN temp_currency_id TO currency_id;
            
            -- Add foreign key constraints
            ALTER TABLE products_productprice ADD CONSTRAINT products_productprice_price_type_id_fk 
            FOREIGN KEY (price_type_id) REFERENCES prices_pricetype(id) ON DELETE PROTECT;
            
            ALTER TABLE products_productprice ADD CONSTRAINT products_productprice_currency_id_fk 
            FOREIGN KEY (currency_id) REFERENCES prices_currency(iso_code) ON DELETE PROTECT;
            """,
            reverse_sql="""
            -- Add back the original columns
            ALTER TABLE products_productprice ADD COLUMN price_type varchar(20);
            ALTER TABLE products_productprice ADD COLUMN currency varchar(3);
            
            -- Populate them from the FK columns
            UPDATE products_productprice pp 
            SET price_type = pt.code
            FROM prices_pricetype pt
            WHERE pp.price_type_id = pt.id;
            
            UPDATE products_productprice pp
            SET currency = pp.currency_id;
            
            -- Drop the FK constraints
            ALTER TABLE products_productprice DROP CONSTRAINT products_productprice_price_type_id_fk;
            ALTER TABLE products_productprice DROP CONSTRAINT products_productprice_currency_id_fk;
            
            -- Drop the FK columns
            ALTER TABLE products_productprice DROP COLUMN price_type_id;
            ALTER TABLE products_productprice DROP COLUMN currency_id;
            """
        ),
    ] 